"""week2 clean listings facts graph

Revision ID: 8032b6027123
Revises: 8750eb3aca2c
Create Date: 2026-07-27 22:57:23.343636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8032b6027123'
down_revision: Union[str, None] = '8750eb3aca2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_entities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('canonical_key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'canonical_key', name='uq_graph_entity')
    )
    op.create_index(op.f('ix_graph_entities_entity_type'), 'graph_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_graph_entities_tenant_id'), 'graph_entities', ['tenant_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('src_id', sa.String(length=32), nullable=False),
    sa.Column('dst_id', sa.String(length=32), nullable=False),
    sa.Column('edge_type', sa.String(length=30), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_row_id', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.String(length=30), nullable=False),
    sa.Column('valid_to', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['graph_entities.id'], ),
    sa.ForeignKeyConstraint(['src_id'], ['graph_entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'src_id', 'dst_id', 'edge_type', name='uq_graph_edge')
    )
    op.create_index('ix_graph_edges_dst', 'graph_edges', ['tenant_id', 'dst_id'], unique=False)
    op.create_index('ix_graph_edges_src', 'graph_edges', ['tenant_id', 'src_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_tenant_id'), 'graph_edges', ['tenant_id'], unique=False)
    op.create_table('clean_listings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('source_row_id', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=30), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('property_type', sa.String(length=30), nullable=False),
    sa.Column('project_slug', sa.String(length=120), nullable=True),
    sa.Column('project_confidence', sa.Float(), nullable=False),
    sa.Column('building_code', sa.String(length=20), nullable=True),
    sa.Column('unit_type_key', sa.String(length=60), nullable=True),
    sa.Column('ward', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('total_price_vnd', sa.Float(), nullable=True),
    sa.Column('price_per_m2_vnd', sa.Float(), nullable=True),
    sa.Column('price_confidence', sa.String(length=20), nullable=False),
    sa.Column('price_evidence', sa.Text(), nullable=False),
    sa.Column('legal_facts', sa.JSON(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('title_clean', sa.Text(), nullable=False),
    sa.Column('description_clean', sa.Text(), nullable=False),
    sa.Column('description_len', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('dedup_cluster_id', sa.String(length=32), nullable=False),
    sa.Column('is_cluster_representative', sa.Boolean(), nullable=False),
    sa.Column('simhash', sa.String(length=16), nullable=False),
    sa.Column('field_flags', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_row_id'], ['source_listings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_row_id', name='uq_clean_listing_source')
    )
    op.create_index(op.f('ix_clean_listings_dedup_cluster_id'), 'clean_listings', ['dedup_cluster_id'], unique=False)
    op.create_index('ix_clean_listings_project', 'clean_listings', ['tenant_id', 'project_slug'], unique=False)
    op.create_index(op.f('ix_clean_listings_source_row_id'), 'clean_listings', ['source_row_id'], unique=False)
    op.create_index(op.f('ix_clean_listings_tenant_id'), 'clean_listings', ['tenant_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('fact_key', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_key', sa.String(length=120), nullable=False),
    sa.Column('predicate', sa.String(length=40), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('parser_version', sa.String(length=30), nullable=False),
    sa.Column('source_row_id', sa.String(length=32), nullable=False),
    sa.Column('source_listing_id', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.String(length=30), nullable=False),
    sa.Column('valid_to', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_row_id'], ['source_listings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'fact_key', name='uq_facts_tenant_key')
    )
    op.create_index(op.f('ix_facts_predicate'), 'facts', ['predicate'], unique=False)
    op.create_index(op.f('ix_facts_source_row_id'), 'facts', ['source_row_id'], unique=False)
    op.create_index('ix_facts_subject', 'facts', ['tenant_id', 'subject_type', 'subject_key'], unique=False)
    op.create_index(op.f('ix_facts_tenant_id'), 'facts', ['tenant_id'], unique=False)
    # Job đã có từ Tuần 1 đều là ingest raw → điền server_default để không phải backfill tay
    op.add_column(
        'ingestion_jobs',
        sa.Column('job_type', sa.String(length=30), nullable=False, server_default='ingest_raw'),
    )
    op.add_column(
        'ingestion_jobs',
        sa.Column('stats', sa.JSON(), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'stats')
    op.drop_column('ingestion_jobs', 'job_type')
    op.drop_index(op.f('ix_facts_tenant_id'), table_name='facts')
    op.drop_index('ix_facts_subject', table_name='facts')
    op.drop_index(op.f('ix_facts_source_row_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_predicate'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_clean_listings_tenant_id'), table_name='clean_listings')
    op.drop_index(op.f('ix_clean_listings_source_row_id'), table_name='clean_listings')
    op.drop_index('ix_clean_listings_project', table_name='clean_listings')
    op.drop_index(op.f('ix_clean_listings_dedup_cluster_id'), table_name='clean_listings')
    op.drop_table('clean_listings')
    op.drop_index(op.f('ix_graph_edges_tenant_id'), table_name='graph_edges')
    op.drop_index('ix_graph_edges_src', table_name='graph_edges')
    op.drop_index('ix_graph_edges_dst', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_graph_entities_tenant_id'), table_name='graph_entities')
    op.drop_index(op.f('ix_graph_entities_entity_type'), table_name='graph_entities')
    op.drop_table('graph_entities')
    # ### end Alembic commands ###
