"""week5 content review and adapter columns

Revision ID: 804d7f4deca9
Revises: d715c20e509f
Create Date: 2026-07-29 11:08:48.508367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '804d7f4deca9'
down_revision: Union[str, None] = 'd715c20e509f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_slug', sa.String(length=120), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('persona', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_tenant_id'), 'content_items', ['tenant_id'], unique=False)
    op.create_index('ix_content_items_tenant_status', 'content_items', ['tenant_id', 'status'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('content_item_id', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.String(length=32), nullable=True),
    sa.Column('config', sa.String(length=4), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('adapter_name', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('claims', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'version_no', name='uq_content_version_no')
    )
    op.create_index(op.f('ix_content_versions_content_item_id'), 'content_versions', ['content_item_id'], unique=False)
    op.create_index('ix_content_versions_tenant', 'content_versions', ['tenant_id', 'content_item_id'], unique=False)
    op.create_index(op.f('ix_content_versions_tenant_id'), 'content_versions', ['tenant_id'], unique=False)
    op.add_column('generations', sa.Column('adapter_name', sa.String(length=120), server_default='', nullable=False))
    op.add_column('generations', sa.Column('adapter_fingerprint', sa.String(length=32), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'adapter_fingerprint')
    op.drop_column('generations', 'adapter_name')
    op.drop_index(op.f('ix_content_versions_tenant_id'), table_name='content_versions')
    op.drop_index('ix_content_versions_tenant', table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_content_item_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index('ix_content_items_tenant_status', table_name='content_items')
    op.drop_index(op.f('ix_content_items_tenant_id'), table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
