"""week4 bm25 postings

Revision ID: 98f8c5885510
Revises: a7aad62eeea9
Create Date: 2026-07-28 20:56:15.466036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '98f8c5885510'
down_revision: Union[str, None] = 'a7aad62eeea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lexical_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_id', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=80), nullable=False),
    sa.Column('tf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lexical_postings_chunk', 'lexical_postings', ['chunk_id'], unique=False)
    op.create_index('ix_lexical_postings_term', 'lexical_postings', ['tenant_id', 'term'], unique=False)
    op.add_column('chunks', sa.Column('lexical_len', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'lexical_len')
    op.drop_index('ix_lexical_postings_term', table_name='lexical_postings')
    op.drop_index('ix_lexical_postings_chunk', table_name='lexical_postings')
    op.drop_table('lexical_postings')
    # ### end Alembic commands ###
