"""week3 fact review trail

Revision ID: a7aad62eeea9
Revises: 4982a1adb98d
Create Date: 2026-07-28 11:01:43.430340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7aad62eeea9'
down_revision: Union[str, None] = '4982a1adb98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facts', sa.Column('reviewed_by', sa.String(length=32), nullable=True))
    op.add_column('facts', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('facts', sa.Column('review_note', sa.Text(), nullable=False, server_default=''))
    op.add_column('facts', sa.Column('original_value_text', sa.Text(), nullable=False, server_default=''))
    op.create_foreign_key(None, 'facts', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        # Bản đầu của migration này lỡ drop mất 2 index của Tuần 3 → tạo lại cho chắc
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_chunks_search_vector ON chunks USING GIN (search_vector)"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_chunks_embedding_hnsw ON chunks "
            "USING hnsw (embedding vector_cosine_ops)"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facts', type_='foreignkey')
    op.drop_column('facts', 'original_value_text')
    op.drop_column('facts', 'review_note')
    op.drop_column('facts', 'reviewed_at')
    op.drop_column('facts', 'reviewed_by')
    op.create_index('ix_chunks_search_vector', 'chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
