"""week4 generations

Revision ID: d715c20e509f
Revises: 98f8c5885510
Create Date: 2026-07-28 21:49:07.225332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd715c20e509f'
down_revision: Union[str, None] = '98f8c5885510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('config', sa.String(length=4), nullable=False),
    sa.Column('retrieval_config', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('persona', sa.String(length=20), nullable=False),
    sa.Column('project_slug', sa.String(length=120), nullable=True),
    sa.Column('clean_listing_id', sa.String(length=32), nullable=True),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('context_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('context_fact_ids', sa.JSON(), nullable=False),
    sa.Column('graph_paths', sa.JSON(), nullable=False),
    sa.Column('router_plan', sa.JSON(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('claims', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_config'), 'generations', ['config'], unique=False)
    op.create_index('ix_generations_tenant_created', 'generations', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_generations_tenant_id'), 'generations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_tenant_id'), table_name='generations')
    op.drop_index('ix_generations_tenant_created', table_name='generations')
    op.drop_index(op.f('ix_generations_config'), table_name='generations')
    op.drop_table('generations')
    # ### end Alembic commands ###
